### ISSUE TITLE
Documentation updates

### ISSUE THREAD

**Issue by sfnuser** [camaraproject/DeviceLocation#102]
**Problem description**
Two issues:
- `lastLocationTime` added in `VerifyLocationResponse` schema needs to be reflected in the examples.
- When `maxAge` conditions fail, it can result in `UNKNOWN` location response as discussed in [here](https://github.com/camaraproject/DeviceLocation/issues/34). However, it is better to capture the conclusion in the specification

**Expected action**
Spec update

**Comment by jlurien** [comment]
@sfnuser please review PR #104
