### ISSUE TITLE
MaxAge: type & format does not align with the OpenAPI specification

### ISSUE THREAD

**Issue by sfnuser** [camaraproject/DeviceLocation#123]
**Problem description**
`MaxAge` data type `type: number` and `format: integer` is conflicting with the [OpenAPI specification](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#dataTypes)

**Expected behavior**
Change `type: integer` and remove the `format`

**Comment by patrice-conil** [comment]
Hi @sfnuser, 
Or we could keep format but with integer32 or integer64.

**Comment by sfnuser** [comment]
Hi @patrice-conil,
Yes. I am happy with that 👍🏼 .

**Comment by jlurien** [comment]
Good catch. As we are not using any `format`  for the rest of integers (MatchRate, Radius, Port), I would keep same approach here.
