### ISSUE TITLE
Use Case For Why User Location  Look-back window is vital.

### ISSUE THREAD

**Issue by nickvenezia** [camaraproject/DeviceLocation#152]

**Comment by nickvenezia** [comment]
@jlurien it was for a use case of the "device location api" which was not "precision marketing"  or "Fraud".  The above is a copy of the MEFFY application which was submitted.

**Comment by jlurien** [comment]
Ok, but to make issues more actionable, please let's try to use of the agreed template for enhancements:

**Problem description**


**Possible evolution**


**Alternative solution**


**Additional context**
