### ISSUE TITLE
Add x-correlator as specified in the guideline

### ISSUE THREAD

**Issue by bigludo7** [camaraproject/DeviceLocation#160]
**Problem description**
A specified in Commonalities we have to add x-correlator in our 3 APIs (see https://github.com/camaraproject/Commonalities/pull/115)

**Expected behavior**
Add in the request:

```
parameters:
        - $ref: '#/components/parameters/x-correlator'
```

Add in all API response:
```
          headers:
            x-correlator:
              $ref: '#/components/headers/x-correlator'
```

**Alternative solution**
No alternative

**Additional context**

**Comment by bigludo7** [comment]
@jlurien This one should be an easy to fix but prefer to have guidance on versioning before to propose any PR.

**Comment by jlurien** [comment]
Yes, we have to align to latest version of the Guidelines, but I prefer to close Release 0.2.0 as it is, and include new changes for upcoming 0.3.0-wip, otherwise we never move forward, because we'd need to create another RC and so on

**Comment by bigludo7** [comment]
> Yes, we have to align to latest version of the Guidelines, but I prefer to close Release 0.2.0 as it is, and include new changes for upcoming 0.3.0-wip, otherwise we never move forward, because we'd need to create another RC and so on

Works for me !
I wait for some sync in next meeting to make any PR on this topic.

**Comment by bigludo7** [comment]
Fixed
