### ISSUE TITLE
subscriptionExpireTime is declared as "required" in the subscription-ends - note, but is optional currently

### ISSUE THREAD

**Issue by maxl2287** [camaraproject/DeviceLocation#161]
**Problem description**
[](https://github.com/camaraproject/DeviceStatus/blob/main/code/API_definitions/device-status.yaml#L82-L84)

In the note for a subscription-ends event the `subscriptionExpireTime` is declared as "required by the requester".
But this request-parameter in POST /subscriptions is not mandatory. 

**Expected behavior**
Remove "required by the requester".

**Comment by jlurien** [comment]
I think that the intention of that "required by the requester" was "if requested by the requester", but with PR that is made more clear.
