### ISSUE TITLE
Are we happy with security scope for geofencing?

### ISSUE THREAD

**Issue by bigludo7** [camaraproject/DeviceLocation#173]
**Problem description**
As of today, in Geofencing API we have:

```
      security:
        - openId:
            - geofencing:subscriptions:write
```

Do this name look good? For me the fact that we 'write' a subscription is not the most relevant information but we need to more precise like `geofencing:subscriptions:read-location`

**Possible evolution**
Change name to `geofencing:subscriptions:read-location`

**Alternative solution**

**Additional context**
Discussion in progress here: https://github.com/camaraproject/Commonalities/issues/163

**Comment by jlurien** [comment]
We will join the discussion in commonalities

**Comment by bigludo7** [comment]
We can close this one as it is solved here: https://github.com/camaraproject/Commonalities/blob/main/documentation/API-design-guidelines.md#102-security-implementation - part b)
