### ISSUE TITLE
Circle schema does not get referenced in location-verification.yaml

### ISSUE THREAD

**Issue by RobertoSngular** [camaraproject/DeviceLocation#176]
I see that there is a circle schema wich contains the coordinates and the radius but it dont get referenced from anywere in the document.

Probably you want it to be inside the AreaType schema but rigth now it only contains an enum.

**Comment by alpaycetin74** [comment]
![image](https://github.com/camaraproject/DeviceLocation/assets/16305185/e9028e35-7356-42e2-8bb6-63a0f5fd1280)
The Circle schema is used inside the Area schema. The Area schema is mapped to a "Circle" schema if the AreaType equals to CIRCLE enum value.
