### ISSUE TITLE
Mandate '+' in all phoneNumber formats

### ISSUE THREAD

**Issue by bigludo7** [camaraproject/DeviceLocation#177]
**Problem description**
Mandate '+' in all phoneNumber formats
Align with https://github.com/camaraproject/Commonalities/pull/148

**Expected behavior**
Update accordingly the YAML

**Alternative solution**

**Additional context**
@jlurien  As it is a alignement with guidelines I will proposer PR shortly without waiting for next team call.

**Comment by jlurien** [comment]
Thanks for the PR, I see you only fixed verification and retrieval, any reason to not fix geofencing as well?
