### ISSUE TITLE
Subscription for Location Area

### ISSUE THREAD

**Issue by NoelWirzius** [camaraproject/DeviceLocation#18]
**Summary**
===========
Create a subscription mode for the DeviceLocation API. So that developers are informed if a device is leaving or entering the "radius". This is important for tracking devices for Presetting of Homesettings or for tracking of logistics and more. 

**Changes** 
==========
For this there are several changes to be done

* Adding new paths `/subscriptions`
  * Brining in new optional parameter
    * Based on `/verify` 
    * `EventType` is an array which is giving the subscription mode 
      * `AREA_ENTERED` = the device is leaving the defined radius 
      * `AREA_LEFT` = the device is entering the defined radius 
    * ExpireTime to set how long the subscription should be active 
  *  Activate Multiple Devices and Multiple Events

**Comment by bigludo7** [comment]
Hello @NoelWirzius 
I'm also interested to contribute.

For the area definition, do you think we can stick to the radius or do we have to extend with polygon (or multi polygon) definition ?

**Comment by RogerJL** [comment]
How many devices should one be able to subscribe too?
Suppose all companies subscribes to all their registered users - ready to push ads when entering...

Note: I think the EventTypes are mixed up in the suggestion.

**Comment by akoshunyadi** [comment]
As decided in https://github.com/camaraproject/DeviceLocation/issues/64 the endpoint should be implemented in a separate API
The name is to be discussed

**Comment by shilpa-padgaonkar** [comment]
please check this and provide feedback https://github.com/camaraproject/Commonalities/issues/8#issuecomment-1629615969

**Comment by jgarciahospital** [comment]
Please considere this message as a formal inclusion of the GSMA OGW Product WS request to include Subscription/notification mechanism as part of OGW services. 

https://github.com/camaraproject/Commonalities/issues/8#issuecomment-1642419272

For the specific case of location verification, the request includes device location verification API to include such subscription/notification mechanism, which is usually called "geofencing" in certain fora. Examples of such funcionality in trems of input-outputs are also included, to be aligned with current subscription mechanism in this API. 

Additional context
More details included in the formal request file, attached:

[Camara Submission - Subscription_Notifications v2.docx](https://github.com/camaraproject/DeviceLocation/files/12098193/Camara.Submission.-.Subscription_Notifications.v2.docx)

**Comment by ukkaps** [comment]
I guess areas should be pre-defined from network, hence developer should be able to retrieve the available areas defined in a CSP network to get subscribed to (i.e. a concert area/ Mall area). Developers won't be able to define new geofences or request for areas.

I stand to be corrected.
