### ISSUE TITLE
Geofencing - Align with new model

### ISSUE THREAD

**Issue by bigludo7** [camaraproject/DeviceLocation#200]
**Problem description**
We have decided some months ago to move to CloudsEvent model for subscription. Now, the documentation is available in commonalities, in the [design document](https://github.com/camaraproject/Commonalities/blob/main/documentation/API-design-guidelines.md#121-subscriptionl), and with a [yaml template](https://github.com/camaraproject/Commonalities/blob/main/artifacts/camara-cloudevents/event-subscription-template.yaml).

Our Geofencing API should now be updated accordingly to this new model.

**Expected behavior**

Align geofencing API with this model.
This move will de facto solve #124 

**Alternative solution**

**Additional context**

@maxl2287 as you did a great job on this API could we expect you to continue the work for this issue?

**Comment by maxl2287** [comment]
I will take it in account and try to resolve it asap 🫡

**Comment by maxl2287** [comment]
@bigludo7 PR is open, if you want to take a look. 🚀

**Comment by bigludo7** [comment]
> @bigludo7 PR is open, if you want to take a look. 🚀

Thanks @maxl2287 ! This is great.
I've also do the same work for simswap-subscription so if you can take a look [here](https://github.com/camaraproject/SimSwap/pull/111).
As we're both 'pionner' on this work probably good that we're aligned :)
