### ISSUE TITLE
Provide API readiness checklist

### ISSUE THREAD

**Issue by bigludo7** [camaraproject/DeviceLocation#220]
**Problem description**
To release an API version, an API Sub Project needs to provide the required release assets as specified in the API Readiness Checklist. Source [here](https://wiki.camaraproject.org/display/CAM/API+Release+Process#APIReleaseProcess-APIreadinesschecklist) §API readiness checklist

The template for the checklist is the [API-Readiness-Checklist.md](https://github.com/camaraproject/ReleaseManagement/blob/main/documentation/API-Readiness-Checklist.md) file located in the CAMARA / ReleaseManagement / documentation repository.

**Expected action**
Create md file checklist

**Additional context**
@jlurien @maxl2287  I've created one issue but we'll need 3 files - one for each API - If we prefer to have 3 separate issues I'm fine with it.

**Comment by jgarciahospital** [comment]
Added readiness checklist for location-verification in #226 to include as stable version as fulfilling the required pre-requirements to follow such versioning.

v0.3.0 will then become stable, to validate all the checklist including documentation items.
