### ISSUE TITLE
Add an “Area” data-type into CAMARA_common.yaml

### ISSUE THREAD

**Issue by tlohmar** [camaraproject/DeviceLocation#225]
**Problem description**
Commonalities started the discussion of adding an `Area` Data-Type into CAMARA_common.yaml, in [Issue #242](https://github.com/camaraproject/Commonalities/issues/242).
A couple of potential modifications and extensions are identified. Please provide your views on the issue. 

**Expected action**
Please provide your views on the issue.

**Comment by rartych** [comment]
Please review the PR for this issue https://github.com/camaraproject/Commonalities/pull/315 .

**Comment by jlurien** [comment]
DeviceLocation model has been adopted by Commonalities, so we don't need to update anything
