### ISSUE TITLE
Evolution of Area definition

### ISSUE THREAD

**Issue by jlurien** [camaraproject/DeviceLocation#26]
Derived from discussion in #24

So far (as of v0.1.0), we have 3 properties to define the area, which is always a circle centered in (`latitude`, `longitude`) with radius `accuracy`:

        latitude:
          $ref: '#/components/schemas/Latitude'
        longitude:
          $ref: '#/components/schemas/Longitude'
        accuracy:
          $ref: '#/components/schemas/Accuracy

In order to support more areas, we can consider Area as a polymorphic object, for example:

```
Area:
  description: The geometrical area considered for device location
  oneOf:
    - $ref: '#/components/schemas/Circle'
    - $ref: '#/components/schemas/Polygon'
    - $ref: '#/components/schemas/PostCode'
  discriminator:
    propertyName: type   
```

Apart from the current Circle, there are proposals to support Polygon (Orange) and PostCode (Telefónica)

**Comment by bigludo7** [comment]
Very strange @maxl2287 - I cannot assign you to this issue !

**Comment by bigludo7** [comment]
I've discussed with people familiar with this topic and they pointed me to : https://geojson.org/ 
Seems good materiel to start with something and not far to what we have.

**Comment by jlurien** [comment]
I can take care of this task @bigludo7. Good to have some standard to look into.

I will make a first PR just adding support for a new object `Area`, which by now it can only be a Circle. This can be then reference in the Subscriptions PR, and we can work later on expanding other sub-types of Area in separate tracks.

**Comment by jlurien** [comment]
Closing issue as new Polymorphic model for Area is already merged
