### ISSUE TITLE
Path name

### ISSUE THREAD

**Issue by rartych** [camaraproject/DeviceLocation#30]
Currently we have defined   `/verify` path .
According to OpenAPI Guide and Design Guidelines path should be the name of resources (be a plural noun - _Verbs are not allowed_)
We have ` operationId: verifyLocation` which is correct.

The path name should be changed to for example:
` /verification`
or event more correct: 
` /verifications`

The full URI will look like that:

       http://localhost:9091/location/v0/verifications

This isssue is related to https://github.com/camaraproject/DeviceLocation/issues/15 (alignment with guidelines)

**Comment by jlurien** [comment]
In general there may be cases where we need to expose an operation which is not strictly a resource, such as triggering an action. For that it is common to define a POST /action. This is quite common (https://restful-api-design.readthedocs.io/en/latest/methods.html#actions)
However, in this specific case, we may consider that we are requesting to "create a new verification", and change the path to POST /verifications. To me it is in the limit. Wdyt @bigludo7?

**Comment by bigludo7** [comment]
Hello @jlurien 
Same for me - we can consider creating a new check each time & as Camara guidelines mandates both plural and no verb, `/verifications` is good enough.

**Comment by jlurien** [comment]
@rartych Please open a new PR to contribute with this change. Let's give us this week to work on the open issues and PRs and on our next meeting next week Tuesday, we can decide what to merge.
