### ISSUE TITLE
MaxAge and timestamp for location verification

### ISSUE THREAD

**Issue by akoshunyadi** [camaraproject/DeviceLocation#34]
We would like to add 2 new parameters to the location verification:

**Request**: 
- maxAge: optional, if given it should be considered as the maximum age of the location information which is accepted for the verification

**Response**:
- lastLocationTime: mandatory, timestamp of the last location information

**Comment by jlurien** [comment]
Some comments:

* If age ( lastKnownLocation ) > maxAge -> What would be the expected response?
* Making lastLocationTime mandatory has impact on privacy as we are disclosing when the device was located. This may be sensible.

**Comment by akoshunyadi** [comment]
Getting back to this issue... 
@jlurien 
- if the available location data is too old, then I suggest to deliver "UNKNOWN" as if we had no location data at all.
- lastLocationTime: I'm not sure about that, if it is more sensible than the location verification itself.

**Comment by jlurien** [comment]
> Getting back to this issue... @jlurien
> 
> * if the available location data is too old, then I suggest to deliver "UNKNOWN" as if we had no location data at all.
> * lastLocationTime: I'm not sure about that, if it is more sensible than the location verification itself.

If age ( lastKnownLocation ) > maxAge, then response should be {"verificationResult": "UNKNOWN", "lastLocationTime": "*whatever*" }, or just unknown?

**Comment by bigludo7** [comment]
@akoshunyadi I need to understand more `lastLocationTime` and `maxAge ` behavior

Suppose you check device '0123456789' location at x,y with `maxAge` set to 4h.
The request is performed April 25th at 10 am.

In the network, we are able to retrieve following information: 
the device was at x,y April 25th at 7:30 am.
the device was at z,k April 25th at 10:00 am

Do you expecting in this case:

- to have `verificationResult `true or false ? the device was in the area within the max age but not anymore right now.
- to have `lastLocationTime  `valued in the answer to April 24th - 7:30 am or 10 am ?

for, right now, it adds one additional layer of complexity that we should clarify.
Thanks !

**Comment by bigludo7** [comment]
@akoshunyadi Thanks for the clarification.

**Comment by nickvenezia** [comment]
For location pull, is the output also include elevation?

X-axis
Y-axis
And Z-axis for horizontal?

**Comment by jlurien** [comment]
> For location pull, is the output also include elevation?
> 
> X-axis Y-axis And Z-axis for horizontal?

Not related to this issue, but it doesn't

**Comment by ravishekharcisco** [comment]
The maxAge can be used as a trigger the verification request again. The only challenge, I see is defining the unit for maxAge. For mobile devices it could be minutes where as for few of the static IoT devices even days is good enough.

**Comment by ravishekharcisco** [comment]
I am supportive of the idea of lastLocationTime but it should not be mandatory. Also, can we change the scope of this parameter to have something like the device is in the current location since lastLocationTime. That way we would know since when the device is in current location.

**Comment by jlurien** [comment]
> I am supportive of the idea of lastLocationTime but it should not be mandatory. Also, can we change the scope of this parameter to have something like the device is in the current location since lastLocationTime. That way we would know since when the device is in current location.

I don't think we can assure whether the device is *still* in the same location it was at `lastLocationTime` or it has moved but new location is not known. So we we can return "last known location" at "last location time"
