### ISSUE TITLE
Provide raw location in geographical coordinates

### ISSUE THREAD

**Issue by JoachimDahlgren** [camaraproject/DeviceLocation#40]
Originating from the brief discussion in the meeting 2023-03-14.

In addition to being able to verify the location, Ericsson propose that a developer should also be able to get the raw location information of a device as known by the network.

This would serve use cases in which the device does not have built in GNSS support. Extended with subscription support it would also serve use cases for tracking such devices.

Location data should be provided in form of geographical coordinates (x, y, z). The reason for this is that network identities such as CellID etc. are typically not known by developers (and should perhaps not even be exposed externally). The location could be given as a point or a shape with uncertainty area.

Location is in most jurisdictions considered to be sensitive data and thereby consent by device owner/user must be verified before providing it to the developer.

Further more we believe that the API to access location data should be aligned with API to get device status information to make it easy for developers to request these at the same time (originally we have proposed them as one and the same API https://github.com/camaraproject/DeviceStatus/issues/17

Location could be reported as for instance (but not limited to)

{
       "ageOfLocationInfo": 0,
             "geographicArea": {
             "shape": "POINT",
             "point": {
                     "lon": -180,
                     "lat": -90
              }
      }
}

or 

{
       "ageOfLocationInfo": 10,
             "geographicArea": {
             "shape": "POINT_UNCERTAINTY_CIRCLE",
             "point": {
                     "lon": -180,
                     "lat": -90
              },
             "uncertainty": 200
      }
}

**Comment by NoelWirzius** [comment]
Hey Joachim, 
I like the idea from a Use-Case view. 

My two cents: 
In the end we should make clear that these are two different Endpoints, where we also can have also different consent layers on top. 
The "Verify" is much more easy in consent behavior(workers council...) in a B2B then giving out a "real" Location.

**Comment by jlurien** [comment]
Agree that this is very sensitive so we have to separate endpoints at least, with different scopes. Not sure about if it could even be a different API Device Location vs Device Location Verification, and how to relate this with Device Status.

Regarding how location could be provided, we could reuse the same Area model, that now is polymorphic. Probably networks can not determine a single point, the minimum could be a Circle (estimated location + accuracy)

**Comment by bigludo7** [comment]
Raised in Commonalities --> https://github.com/camaraproject/WorkingGroups/issues/178

**Comment by bigludo7** [comment]
Tracked here: https://github.com/camaraproject/DeviceLocation/pull/55
