### ISSUE TITLE
Update location.yaml to include MaxLocationAge 

### ISSUE THREAD

**Issue by ukkaps** [camaraproject/DeviceLocation#42]
Allow consumer to request the maximum accepted age of the verified location from the operator.

```
  schemas:
    VerifyLocationRequest:
      type: object
      properties:
        ueId:
          $ref: '#/components/schemas/UeId'
        uePort:
          $ref: '#/components/schemas/Port'
        latitude:
          $ref: '#/components/schemas/Latitude'
        longitude:
          $ref: '#/components/schemas/Longitude'
        accuracy:
          $ref: '#/components/schemas/Accuracy'
        maxLocationAge:
          $ref: '#/components/schemas/MaxAge'
      required:
        - ueId
        - latitude
        - longitude
        - accuracy
        - maxAge 
```
```
MaxAge:
      description: Max location aging validity required by the application in Minute, Default =0 for realtime location
      type: number
      minimum: 0
      maximum: 1440
      example: 30
```

**Comment by jlurien** [comment]
Hi @ukkaps 

Some comments

- if it is `required` then describing a default value makes no sense. We have to decide which one is best approach. To me, the options are:

  a) Make it optional and defining a `default` which is NOT real-time, e.g. 5 to 10 minutes, so implementations may rely by default on some passive data. If client explicitly requires real-time location, `maxAge=0`, then it must be added to the request.

  b) Making it required, without default indication. In this case, I wonder in which use cases clients would ask for a value other than 0, which is the most accurate.

- As part of this new feature, we have to model also the expected server behaviour and the responses: Some questions:

  -  If requested `maxAge` cannot be satisfied, should implementation return 200 + `verificationResult` with some adhoc value, or an error?  
  - Should we include some indication of `locationAge` in the response in any case?

**Comment by jlurien** [comment]
@ukkaps This issue duplicates #34, we can consolidate all discussions there. I'm closing this one as duplicate.

**Comment by jlurien** [comment]
Duplicate
