### ISSUE TITLE
Include locationType as a request parameter.

### ISSUE THREAD

**Issue by ukkaps** [camaraproject/DeviceLocation#43]
Include locationType as a request parameter to extend location verification for the following business use cases. Can assign numbers as identifiers for location type. 

ex:
- Real time location.
- Office/work location (most latched site/location in the day time).
- Home location (most latched site/location in the night time).

**Comment by jlurien** [comment]
@ukkaps Could you elaborate further on how this location type is related to the the location verification endpoint? Which is the only use case that we are currently covering. Or are you proposing a new endpoint to disclose the user location in real time, or the most common user locations at certain period?

**Comment by jlurien** [comment]
@ukkaps, take a look at issue #40, which is about providing location. If you petition is in line with that one, we can close this.
