### ISSUE TITLE
Fix error code with Guidelines

### ISSUE THREAD

**Issue by bigludo7** [camaraproject/DeviceLocation#45]
For now we are not using the right code (as defined in the guidelines) for error in the OAS examples.

For 400 should be INVALID_ARGUMENT instead of INVALID_INPUT
for 401 ... UNAUTHENTICATED and not UNAUTHORIZED
same mismatch for 403, 500 & 503

This indirectly link to #15 

@jlurien as it is only example change I can probably fix this now without changing version no?

**Comment by jlurien** [comment]
Yes, fix it in 0.2
