### ISSUE TITLE
Differentiate basePaths for APIS for location verification vs location retrieval

### ISSUE THREAD

**Issue by jlurien** [camaraproject/DeviceLocation#59]
Our [current spec](https://github.com/camaraproject/DeviceLocation/blob/main/code/API_definitions/location.yaml) uses `basePath` =  `location`, but we are now [proposing a new API](https://github.com/camaraproject/DeviceLocation/pull/55) within this WG, and as they are separate APIs they must have different `basePath`.
 
Proposal is to rename current one to `location-verification` and the new one could keep just `location`, or even `location-retrieval`, to make it more explicit.

Thoughts, preferences?

**Comment by sfnuser** [comment]
I agree with `location-verification` rename and the new one shall be `location` as it is a `GET`.

I also wonder why `basePath` needs to be a variable in the spec. Can it not be hardcoded?

**Comment by nickvenezia** [comment]
When location is recorded, should it be recorded who requested the info?

**Comment by jlurien** [comment]
> When location is recorded, should it be recorded who requested the info?

How is that question related to this issue? Feel free to open new issues to raise anything new so people can focus on the topic.

**Comment by jlurien** [comment]
To be updated as `device-location-verification`
