### ISSUE TITLE
Meetings ?

### ISSUE THREAD

**Issue by GarethWGSMA** [camaraproject/DeviceLocation#6]
hi,

do we have an meetings arrange for this working group ? I can't find a link.

Thanks,
Gareth

**Comment by MarkusKuemmerle** [comment]
Would you please insert the meeting data in the Readme.md of the Sub Project?

**Comment by jlurien** [comment]
We do not have a slot for meetings yet, I will sent some proposals to the mailing list to find one.

**Comment by bigludo7** [comment]
Thanks @jlurien  - I will help for meeting hosting & minutes ;)

**Comment by jlurien** [comment]
Meetings set on Tuesdays 9AM CET. Details added with PR: https://github.com/camaraproject/DeviceLocation/pull/13
