### ISSUE TITLE
Units for radius

### ISSUE THREAD

**Issue by jlurien** [camaraproject/DeviceLocation#60]
Currently is kilometers [km] but there is a proposal to use meters [m] instead

Opinions?

**Comment by bigludo7** [comment]
I have no enough technical background to provide a precise answer but my understanding is cell tower triangulation precision at best is around 300/500 meters with sometimes a 150 m precision in city where there is a high density of tower. But it could be several kilometers in rural area.

My 2 cents: I tend to think that km radius is just good enough and not provided unrealistic promise.

**Comment by alpaycetin74** [comment]
There are a variety of location technologies available , some of which may provide very accurate results within a radius of a few meters. I believe we favor the more accurate systems and go with meters.

**Comment by JoachimDahlgren** [comment]
It would be beneficial if we can use the same unit in both verify location and "retrieve device location" and I would then prefer to use meters as accuracy will differ depending on the situation and which underlying system might be used.

**Comment by jlurien** [comment]
Related to this is that currently the location verification  API specifies a minimum for accuracy of 2 km. If we move to meter we should probably review this limit as well.

**Comment by bigludo7** [comment]
> Related to this is that currently the location verification API specifies a minimum for accuracy of 2 km. If we move to meter we should probably review this limit as well.

This is exactly that make me a bit nervous about this switch.... for me we should align on the 'minimal' capability and not the 'best' one (based on gmlc for example) in order to get as many as possible telco implementations.  And so in this case we have to consider use of cell-based location. What about using meter is our accuracy is around 500 meters (and we did not have this 500 meters accuracy in remote place) ?

**Comment by jlurien** [comment]
I'm waiting for some internal feedback, but in case that now or in a near future, accuracy for this type of service may be in the order of 100s of meters in some cases, it would may sense to define accuracy as, for example:

description: accuracy in meters [m]
type: integer
minimum: 500  

even if we have to return 5000 in other cases

**Comment by bigludo7** [comment]
Discussion occurred in Jun 20th call --> use meter
