### ISSUE TITLE
Adding subscription in existing 'location verification' API or adding a new API

### ISSUE THREAD

**Issue by bigludo7** [camaraproject/DeviceLocation#64]
Team,
We need a decision about introduction of 'geo fencing' notification endpoint.
We have 2 options:

1. Add this subscription endpoint in existing 'location verification' API
2. Create a whole new API for that.

From my perspective
Functionally, checking location & notification management for geofencing are very close and share a lot of in common.
From a business perspective, we'll probably have separate business case and model.

I tend to prefer option 1 to not multiply the API and we are in very similar context.
Please provide feedback in order to get discussion/decision in next meeting.

cc: @ukkaps

**Comment by jgarciahospital** [comment]
(Also from product perspective) Since the use cases / services to implement can be so different, our option is also implementing different APIs.

**Comment by alpaycetin74** [comment]
Implementing different APIs would also help them to evolve independently.

**Comment by bigludo7** [comment]
Team decision from June 20th meeting: We opt to have 2 distinct APIs.
