### ISSUE TITLE
Remodel Area as inheritance

### ISSUE THREAD

**Issue by jlurien** [camaraproject/DeviceLocation#72]
**Problem description**

Area uses a polymorphic model (oneOf)

**Expected behavior**

Guidelines favor inheritance (allOf) 

**Alternative solution**

Remodel Area a base class and Circle as child

**Additional context**

**Comment by jlurien** [comment]
@bigludo7 I realise that here we use also oneOf instead of allOf. I guess we'll have to align with ongoing discussions elsewhere.

**Comment by bigludo7** [comment]
@jlurien Yes. 

I'm reviewing quickly PR#71 - we can perhaps first merge this one and after manage removal oneOf.

I do not have oneOf in raw location API (I sent a reminder to move on this one also).
