### ISSUE TITLE
Accuracy Levels for Device Location APIs

### ISSUE THREAD

**Issue by gmuratk** [camaraproject/DeviceLocation#78]
**Problem description**
Different accuracy levels should be supported from privacy perspective as each Telco may have different policies.

**Possible evolution**
Define a way to offer different accuracy levels for the Device Location APIs (one time or subscription based) (i.e. precise, coarse).

**Alternative solution**
n/a

**Additional context**
https://github.com/camaraproject/DeviceLocation/issues/58#issuecomment-1622330925

**Comment by jlurien** [comment]
Discussed during [last meeting](https://github.com/camaraproject/DeviceLocation/blob/main/documentation/MeetingMinutes/MoM-2023-07-18.md#accuracy-levels-for-device-location-apis)

* Not sure about the relevance of the problem with current technology as we're not able to provide 'fine-grain' location.

**Comment by bigludo7** [comment]
No update for last 3 months.
