### ISSUE TITLE
Test Cases and Code Snippets.

### ISSUE THREAD

**Issue by questsin** [camaraproject/DeviceLocation#80]
As far as I know, this repo does not follow point 5 of that guide as no Gherkin or test cases are provided as required. PR#79 was an attempt to remedy this. As per @jlurien "HTML file as part of the documentation is not the way to manage them."

As per API-DocumentationTemplate, code snippets are also encouraged and this commit also provides that.

_Originally posted by @questsin in https://github.com/camaraproject/DeviceLocation/issues/79#issuecomment-1625435152_

As a provider implementor from 5GFF and Rogers Communications, contributions from our Compliance and Conformance test bed fulfill the minimum readiness criteria w.r.t API test cases and documentation, including in the Gherkin Style.
This can be easily translated to any language and framework of the day. It's just a start, but based on our real-life implementations and inspired by TMForum conformance and compliance tests in the same framework.
It's also self-contained and includes all the bells and whistles, batteries included, and can run anywhere 😀

Suggest we provide these tests covering all major languages, including code snippets of their use.

**Comment by jlurien** [comment]
Discussed during [last meeting](https://github.com/camaraproject/DeviceLocation/blob/main/documentation/MeetingMinutes/MoM-2023-07-18.md#test-cases).

Not to be covered yet for current releases v0.x, but have to be aligned with the outcome of commonalities before v1.0
